apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: airbnb-system
data:
  DB_HOST: "mongodb-service"
  DB_PORT: "27017"
  DB_NAME: "airbnb_core"
  DB_USER: "admin"
  # Password comes from secret

