apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: airbnb-system
  labels:
    app: kafka
data:
  KAFKA_BROKER: "kafka-service:9092"
  KAFKA_INTERNAL_BROKER: "kafka-service:9093"
  ZOOKEEPER_CONNECT: "zookeeper-service:2181"

