apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-agent-config
  namespace: airbnb-system
data:
  PORT: "8000"
  HOST: "0.0.0.0"
  TRAVELER_API_URL: "http://traveller-backend-service:5001"
  DB_NAME: "agent_airbnb.db"
  ALLOWED_ORIGINS: "http://a7a83e8e4cc8843009bccdfeda27b3fa-80434930.us-east-1.elb.amazonaws.com,http://abe6856d8cc9d449eb0e420eef657eb2-612137670.us-east-1.elb.amazonaws.com,http://localhost:5174,http://localhost:5173"

