apiVersion: v1
kind: Namespace
metadata:
<<<<<<< HEAD
  name: airbnb-system
  labels:
    name: airbnb-system
=======
  name: airbnb-production
  labels:
    name: airbnb-production
    environment: production
    managed-by: kubernetes
>>>>>>> 4dd375e (Add Kubernetes namespace and ConfigMap for airbnb application)

