apiVersion: v1
kind: Service
metadata:
  name: host-frontend-service
  namespace: airbnb-system
  labels:
    app: host-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: host-frontend

