USE airbnb_core;

-- Helper to add column if missing
SET @schema := DATABASE();

-- Owners
SET @tbl := 'owners';
SET @col := 'street';
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@schema AND TABLE_NAME=@tbl AND COLUMN_NAME=@col)=0,
  'ALTER TABLE owners ADD COLUMN street VARCHAR(255);','SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @col := 'unit';
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@schema AND TABLE_NAME=@tbl AND COLUMN_NAME=@col)=0,
  'ALTER TABLE owners ADD COLUMN unit VARCHAR(100);','SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @col := 'city';
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@schema AND TABLE_NAME=@tbl AND COLUMN_NAME=@col)=0,
  'ALTER TABLE owners ADD COLUMN city VARCHAR(120);','SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @col := 'state';
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@schema AND TABLE_NAME=@tbl AND COLUMN_NAME=@col)=0,
  'ALTER TABLE owners ADD COLUMN state VARCHAR(80);','SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @col := 'zip';
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@schema AND TABLE_NAME=@tbl AND COLUMN_NAME=@col)=0,
  'ALTER TABLE owners ADD COLUMN zip VARCHAR(20);','SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @col := 'country';
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@schema AND TABLE_NAME=@tbl AND COLUMN_NAME=@col)=0,
  'ALTER TABLE owners ADD COLUMN country VARCHAR(80);','SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;

-- Properties
SET @tbl := 'properties';
SET @col := 'property_type';
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@schema AND TABLE_NAME=@tbl AND COLUMN_NAME=@col)=0,
  'ALTER TABLE properties ADD COLUMN property_type VARCHAR(50);','SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @col := 'privacy_type';
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@schema AND TABLE_NAME=@tbl AND COLUMN_NAME=@col)=0,
  'ALTER TABLE properties ADD COLUMN privacy_type VARCHAR(20);','SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @col := 'max_guests';
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@schema AND TABLE_NAME=@tbl AND COLUMN_NAME=@col)=0,
  'ALTER TABLE properties ADD COLUMN max_guests INT;','SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @col := 'beds';
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@schema AND TABLE_NAME=@tbl AND COLUMN_NAME=@col)=0,
  'ALTER TABLE properties ADD COLUMN beds INT;','SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @col := 'latitude';
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@schema AND TABLE_NAME=@tbl AND COLUMN_NAME=@col)=0,
  'ALTER TABLE properties ADD COLUMN latitude DECIMAL(10,8);','SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @col := 'longitude';
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@schema AND TABLE_NAME=@tbl AND COLUMN_NAME=@col)=0,
  'ALTER TABLE properties ADD COLUMN longitude DECIMAL(11,8);','SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @col := 'street';
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@schema AND TABLE_NAME=@tbl AND COLUMN_NAME=@col)=0,
  'ALTER TABLE properties ADD COLUMN street VARCHAR(255);','SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @col := 'unit';
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@schema AND TABLE_NAME=@tbl AND COLUMN_NAME=@col)=0,
  'ALTER TABLE properties ADD COLUMN unit VARCHAR(100);','SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @col := 'city';
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@schema AND TABLE_NAME=@tbl AND COLUMN_NAME=@col)=0,
  'ALTER TABLE properties ADD COLUMN city VARCHAR(120);','SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @col := 'state';
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@schema AND TABLE_NAME=@tbl AND COLUMN_NAME=@col)=0,
  'ALTER TABLE properties ADD COLUMN state VARCHAR(80);','SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @col := 'zip';
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@schema AND TABLE_NAME=@tbl AND COLUMN_NAME=@col)=0,
  'ALTER TABLE properties ADD COLUMN zip VARCHAR(20);','SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @col := 'country';
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@schema AND TABLE_NAME=@tbl AND COLUMN_NAME=@col)=0,
  'ALTER TABLE properties ADD COLUMN country VARCHAR(80);','SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @col := 'highlights';
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@schema AND TABLE_NAME=@tbl AND COLUMN_NAME=@col)=0,
  'ALTER TABLE properties ADD COLUMN highlights JSON;','SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @col := 'safety';
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@schema AND TABLE_NAME=@tbl AND COLUMN_NAME=@col)=0,
  'ALTER TABLE properties ADD COLUMN safety JSON;','SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @col := 'weekend_premium_percent';
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@schema AND TABLE_NAME=@tbl AND COLUMN_NAME=@col)=0,
  'ALTER TABLE properties ADD COLUMN weekend_premium_percent DECIMAL(5,2) DEFAULT 0;','SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @col := 'discounts';
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@schema AND TABLE_NAME=@tbl AND COLUMN_NAME=@col)=0,
  'ALTER TABLE properties ADD COLUMN discounts JSON;','SELECT 1'); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @col := 'booking_mode';
SET @sql := IF((SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=@schema AND TABLE_NAME=@tbl AND COLUMN_NAME=@col)=0,
  "ALTER TABLE properties ADD COLUMN booking_mode ENUM('APPROVAL','INSTANT') DEFAULT 'APPROVAL';","SELECT 1"); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
