# Kafka Consumer Configuration
bootstrap.servers=localhost:9092
group.id=airbnb-consumer-group
enable.auto.commit=true
auto.commit.interval.ms=1000
key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
auto.offset.reset=earliest
max.partition.fetch.bytes=1048576
session.timeout.ms=30000
heartbeat.interval.ms=10000

